# Generated by Django 2.0 on 2017-12-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('ulr', models.URLField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
            ],
        ),
    ]
