# Generated by Django 2.0 on 2017-12-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='ulr',
            new_name='url',
        ),
    ]
